apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgueugno-playground
  name: pgueugno-playground
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: pgueugno-playground
  type: ClusterIP
