# -*- mode: ruby -*-
# vi: set ft=ruby :

### ENVIRONMENTS
# Vagrant
V_BOX                 = "bento/centos-7.9"
V_PROVIDER            = "virtualbox"
# VIRTUALBOX
VM_CPU                = "1"
VM_MEMORY             = "4096"
# VM
VM_SERVER_HOSTNAME    = "dapintoS"
VM_SERVER_IP          = "192.168.56.110"
#
Vagrant.configure("2") do |config|
  # SSH keys
  config.trigger.before :up, :provision do |trigger|
    trigger.run = { path: "scripts/keygen.sh" }
  end
  # OS
  config.vm.box     = V_BOX
  config.vm.box_url = V_BOX
  # SERVER IN CONTROLLER MODE
  config.vm.define VM_SERVER_HOSTNAME do |server|
    server.vm.network "private_network", ip: VM_SERVER_IP
    server.vm.hostname = VM_SERVER_HOSTNAME
    if V_PROVIDER == "virtualbox"
      server.vm.provider V_PROVIDER do |vb|
        vb.cpus                   = VM_CPU
        vb.memory                 = VM_MEMORY
        vb.linked_clone           = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
        vb.check_guest_additions  = false
        vb.customize ["modifyvm", :id, "--name", VM_SERVER_HOSTNAME]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'None']
      end
      server.vm.provision :shell do |s|
        s.inline = <<-SHELL
        uname -a
        echo "\t\nyum UPDATE...\n"
        yum check-update
        yum -y install net-tools
        yum -y update
      SHELL
      end
      server.vm.provision :shell do |s|
        s.path  = "scripts/k3s_install.sh"
        s.env   = {
          "K3S_MODE"            => "SERVER",
          "VM_SERVER_IP"        => VM_SERVER_IP,
          "VM_SERVER_HOSTNAME"  => VM_SERVER_HOSTNAME,
        }
      end
      server.vm.provision :shell do |s|
        s.path  = "scripts/ingress-nginx.sh"
      end
    end
  end
end
