# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.define "tbaillyS" do |tbaillyS|
    tbaillyS.vm.hostname = "tbaillyS"
    tbaillyS.vm.network "private_network", ip: "192.168.56.110"

    tbaillyS.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
      vb.name = "tbaillyS"
    end 
  end

  config.vm.provision "file", source: "./scripts", destination: "/home/vagrant/scripts"
  config.vm.provision "shell", path: "./scripts/provision.sh"

end
  