# -*- mode: ruby -*-
# vi: set ft=ruby :

V_BOX                 = "bento/centos-7.9"
VM_SERVER_HOSTNAME    = "pgueugnoS"
VM_WORKER_HOSTNAME    = "pgueugnoSW"
VM_SERVER_IP          = "192.168.56.110"
VM_WORKER_IP          = "192.168.56.111"

Vagrant.configure("2") do |config|

  config.vm.box = V_BOX

  # synced folder between host and all VMs
  config.vm.synced_folder "./sync", "/home/vagrant/", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus                   = 1
    vb.memory                 = "1024"
    vb.linked_clone           = true
  end

  # tools package required to install k3s with curl
  config.vm.provision :shell do |s|
    s.inline = <<-SHELL
      uname -a
      echo "\t\n ADD BUSYBOX...\n"
      yum -y install net-tools
    SHELL
  end

  # ! ----------- Server -----------
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.define VM_SERVER_HOSTNAME do |control_server|
    control_server.vm.network "private_network", ip: VM_SERVER_IP
    control_server.vm.hostname = VM_SERVER_HOSTNAME

    # Kubernetes API Access
    control_server.vm.network "forwarded_port", guest: 6443, host: 6443

      # Define the resources for the virtualbox
    control_server.vm.provider "virtualbox" do |vb|
      vb.name = VM_SERVER_HOSTNAME
    end

    # Run setup script to install K3s on VM
    control_server.vm.provision :shell do |s|
      s.path  = "scripts/k3s_install.sh"
      s.env   = {
        "K3S_MODE"            => "SERVER",
        "VM_SERVER_IP"        => VM_SERVER_IP,
        "VM_SERVER_HOSTNAME"  => VM_SERVER_HOSTNAME,
      }
    end
  end

  # ! ----------- Worker -----------

  config.vm.define VM_WORKER_HOSTNAME do |control_worker|
    control_worker.vm.network "private_network", ip: VM_WORKER_IP
    control_worker.vm.hostname = VM_WORKER_HOSTNAME

    # Define the resources for virtualbox
    control_worker.vm.provider "virtualbox" do |vb|
      vb.name = VM_WORKER_HOSTNAME
    end

    # Run setup script to install K3s on VM
    control_worker.vm.provision :shell do |s|
      s.path  = "scripts/k3s_install.sh"
      s.env   = {
        "K3S_MODE"            => "AGENT",
        "VM_SERVER_IP"        => VM_WORKER_IP,
        "VM_SERVER_HOSTNAME"  => VM_WORKER_HOSTNAME,
      }
    end
  end
end