# -*- mode: ruby -*-
# vi: set ft=ruby :

V_BOX                 = "bento/centos-8.5"
V_PROVIDER            = "virtualbox"
VM_CPU                = "1"
VM_MEMORY             = "4096"
VM_SERVER_HOSTNAME    = "dapintoS"
VM_SERVER_IP          = "192.168.56.110"
#
Vagrant.configure("2") do |config|
  config.vm.box     = V_BOX
  config.vm.box_url = V_BOX
  config.vm.define VM_SERVER_HOSTNAME do |server|
    server.vm.network "private_network", ip: VM_SERVER_IP
    server.vm.hostname = VM_SERVER_HOSTNAME
    if V_PROVIDER == "virtualbox"
    server.vm.synced_folder ".", "/vagrant", type:"virtualbox"
      server.vm.provider V_PROVIDER do |vb|
        vb.cpus                   = VM_CPU
        vb.memory                 = VM_MEMORY
        vb.linked_clone           = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
        vb.check_guest_additions  = false
        vb.customize ["modifyvm", :id, "--name", VM_SERVER_HOSTNAME]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ['modifyvm', :id, '--graphicscontroller', 'None']
      end
      server.vm.provision :shell do |s|
        s.path  = "scripts/install_all.sh"
        s.env   = {
          "K3S_MODE"            => "SERVER",
          "VM_SERVER_IP"        => VM_SERVER_IP,
          "VM_SERVER_HOSTNAME"  => VM_SERVER_HOSTNAME,
        }
      end
      server.vm.provision :shell do |s|
        s.path  = "scripts/setup_all.sh"
      end
    end
  end
end
